# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

# Controls when the action will run.
on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Run on every push to the master branch
  push:
    branches:
      - main
      - master
  
  # Also run when manually triggered from the GitHub UI
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v3

      # Generates the snake
      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: ${{ github.repository_owner }}
          # Use the advanced SVG outputs with a more detailed snake
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#ff007b&color_dots=#044289,#0969da,#2188ff,#39d353,#26a641
          
          # Generate a snake with a head and special colors
          snake_color: "#ff007b"
          color_snake_mouth: "#000"
          color_snake_tongue: "#ff0000"
          
          # Use a customized body shape for the snake
          snake_body: "speechbubble"

      # Pushes the content of <build_dir> to the repository's "output" branch
      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
